// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package postgres

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type statsModelTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *statsModelTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("stats").
func (v *statsModelTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *statsModelTableType) Columns() []string {
	return []string{
		"url_id",
		"hits",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *statsModelTableType) NewStruct() reform.Struct {
	return new(statsModel)
}

// NewRecord makes a new record for that table.
func (v *statsModelTableType) NewRecord() reform.Record {
	return new(statsModel)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *statsModelTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// statsModelTable represents stats view or table in SQL database.
var statsModelTable = &statsModelTableType{
	s: parse.StructInfo{
		Type:    "statsModel",
		SQLName: "stats",
		Fields: []parse.FieldInfo{
			{Name: "URLID", Type: "int64", Column: "url_id"},
			{Name: "Hits", Type: "int64", Column: "hits"},
		},
		PKFieldIndex: 0,
	},
	z: new(statsModel).Values(),
}

// String returns a string representation of this struct or record.
func (s statsModel) String() string {
	res := make([]string, 2)
	res[0] = "URLID: " + reform.Inspect(s.URLID, true)
	res[1] = "Hits: " + reform.Inspect(s.Hits, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *statsModel) Values() []interface{} {
	return []interface{}{
		s.URLID,
		s.Hits,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *statsModel) Pointers() []interface{} {
	return []interface{}{
		&s.URLID,
		&s.Hits,
	}
}

// View returns View object for that struct.
func (s *statsModel) View() reform.View {
	return statsModelTable
}

// Table returns Table object for that record.
func (s *statsModel) Table() reform.Table {
	return statsModelTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *statsModel) PKValue() interface{} {
	return s.URLID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *statsModel) PKPointer() interface{} {
	return &s.URLID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *statsModel) HasPK() bool {
	return s.URLID != statsModelTable.z[statsModelTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.URLID = pk.
func (s *statsModel) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = statsModelTable
	_ reform.Struct = (*statsModel)(nil)
	_ reform.Table  = statsModelTable
	_ reform.Record = (*statsModel)(nil)
	_ fmt.Stringer  = (*statsModel)(nil)
)

func init() {
	parse.AssertUpToDate(&statsModelTable.s, new(statsModel))
}
